export PATH="/usr/local/bin:$PATH"
alias k="kubectl"
alias kl="kubelogin"
alias amend="git commit -a -m 'fix' && git reset --soft HEAD~1 && git commit --amend"
alias dcc="docker-compose"
alias d="docker"
alias gsync="~/bin/syncgit.sh" 
alias gs="git status"
alias gc="git checkout"
alias gri="git rebase -i"
alias gbf="git branch -f"
alias gp="git push origin"
alias gr="git rebase"

